name: "Build iOS app"

on: [workflow_dispatch]

jobs:
  build_unsigned:
    runs-on: macos-latest
    steps:
      - name: check Xcode version
        run: /usr/bin/xcodebuild -version

      - name: checkout repository
        uses: actions/checkout@v4

      - name: build archive
        run: |
          xcodebuild -scheme Stoat \
          -skipPackagePluginValidation \
          -skipMacroValidation \
          -archivePath $RUNNER_TEMP/Stoat.xcarchive \
          -sdk iphoneos \
          -configuration Release \
          -destination generic/platform=iOS \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO \
          clean archive

      - name: Upload application
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ runner.temp }}/Stoat.xcarchive
          retention-days: 3
